//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempertureEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TempertureEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Print1 {
            get {
                object obj = ResourceManager.GetObject("Print1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ptRowIcon {
            get {
                object obj = ResourceManager.GetObject("ptRowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ptRowTipIcon {
            get {
                object obj = ResourceManager.GetObject("ptRowTipIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;temperture Genid=&quot;152&quot;&gt;
        ///  &lt;pens&gt;
        ///    &lt;ClsPens Id=&quot;p1&quot; Tname=&quot;blackPen&quot; Pensize=&quot;1&quot; Pencolor=&quot;0,0,0&quot; /&gt;
        ///    &lt;ClsPens Id=&quot;p2&quot; Tname=&quot;lightblackPen&quot; Pensize=&quot;0.1&quot; Pencolor=&quot;150,150,150&quot; /&gt;
        ///    &lt;ClsPens Id=&quot;p3&quot; Tname=&quot;redPen&quot; Pensize=&quot;1&quot; Pencolor=&quot;255,0,0&quot; /&gt;
        ///    &lt;ClsPens Id=&quot;p4&quot; Tname=&quot;bluePen&quot; Pensize=&quot;1&quot; Pencolor=&quot;0,0,255&quot; /&gt;
        ///    &lt;ClsPens Id=&quot;p5&quot; Tname=&quot;blackboldpen&quot; Pensize=&quot;2&quot; Pencolor=&quot;0,0,0&quot; /&gt;
        ///    &lt;ClsPens Id=&quot;p113&quot; Tname=&quot;greedPen&quot; Pensize=&quot;1&quot; Pencolor=&quot;0,128,0&quot; /&gt;
        ///    &lt;ClsPens Id=&quot;p116&quot; Tname [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TempertureSet_new {
            get {
                return ResourceManager.GetString("TempertureSet_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Webcontrol_ConnectionsZone {
            get {
                object obj = ResourceManager.GetObject("Webcontrol_ConnectionsZone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
